export const projectArray = [
  {
    title: "Bachelor of Science (Informatik) - RWTH Aachen",
    shortDesc:
      "Studium an der RWTH Aachen mit diversen praktischen Projekten. Noch mehr Platzhalter Text. Ich muss mal schauen. Na ja.",
    longDesc:
      "Während meines Studiums an der RWTH Aachen habe ich neben vielen theoretischen Grundlagen der Informatik auch einige praktische Erfahrungen im Programmieren gesammelt.\nDarunter fallen die Entwicklung eines Betriebssystems für den Mikrocontroller Atmega 644 in der Programmiersprache C und ein Teamprojekt, in dem wir in einer kleinen Gruppe die Website für ein fiktives Reiseportal entwickelt haben. Dabei habe ich erste Erfahrungen mit JavaScript, HTML, CSS, Github, Docker und Postman gesammelt.",
    tags: [
      { name: "Haskell" },
      { name: "Prolog" },
      { name: "Java" },
      { name: "C" },
      { name: "HTML" },
      { name: "CSS" },
      { name: "JavaScript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Docker" },
      { name: "MySQL" },
      { name: "Postman" },
    ],
  },
  {
    title: "Platzhalter 2",
    shortDesc: "Studium an der RWTH Aachen mit diversen praktischen Projekten",
    longDesc:
      "Während meines Studiums an der RWTH Aachen habe ich neben vielen theoretischen Grundlagen der Informatik auch einige praktische Erfahrungen im Programmieren gesammelt.\nDarunter fallen die Entwicklung eines Betriebssystems für den Mikrocontroller Atmega 644 in der Programmiersprache C und ein Teamprojekt, in dem wir in einer kleinen Gruppe die Website für ein fiktives Reiseportal entwickelt haben. Dabei habe ich erste Erfahrungen mit JavaScript, HTML, CSS, Github, Docker und Postman gesammelt.",
    tags: [
      { name: "Haskell" },
      { name: "Prolog" },
      { name: "Java" },
      { name: "C" },
      { name: "HTML" },
      { name: "CSS" },
      { name: "JavaScript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Docker" },
      { name: "MySQL" },
      { name: "Postman" },
    ],
  },
  {
    title: "Platzhalter 3",
    shortDesc: "Studium an der RWTH Aachen mit diversen praktischen Projekten",
    longDesc:
      "Während meines Studiums an der RWTH Aachen habe ich neben vielen theoretischen Grundlagen der Informatik auch einige praktische Erfahrungen im Programmieren gesammelt.\nDarunter fallen die Entwicklung eines Betriebssystems für den Mikrocontroller Atmega 644 in der Programmiersprache C und ein Teamprojekt, in dem wir in einer kleinen Gruppe die Website für ein fiktives Reiseportal entwickelt haben. Dabei habe ich erste Erfahrungen mit JavaScript, HTML, CSS, Github, Docker und Postman gesammelt.",
    tags: [
      { name: "Haskell" },
      { name: "Prolog" },
      { name: "Java" },
      { name: "C" },
      { name: "HTML" },
      { name: "CSS" },
      { name: "JavaScript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Docker" },
      { name: "MySQL" },
      { name: "Postman" },
    ],
  },
  {
    title: "Platzhalter 4",
    shortDesc: "Studium an der RWTH Aachen mit diversen praktischen Projekten",
    longDesc:
      "Während meines Studiums an der RWTH Aachen habe ich neben vielen theoretischen Grundlagen der Informatik auch einige praktische Erfahrungen im Programmieren gesammelt.\nDarunter fallen die Entwicklung eines Betriebssystems für den Mikrocontroller Atmega 644 in der Programmiersprache C und ein Teamprojekt, in dem wir in einer kleinen Gruppe die Website für ein fiktives Reiseportal entwickelt haben. Dabei habe ich erste Erfahrungen mit JavaScript, HTML, CSS, Github, Docker und Postman gesammelt.",
    tags: [
      { name: "Haskell" },
      { name: "Prolog" },
      { name: "Java" },
      { name: "C" },
      { name: "HTML" },
      { name: "CSS" },
      { name: "JavaScript" },
      { name: "Git" },
      { name: "Github" },
      { name: "Docker" },
      { name: "MySQL" },
      { name: "Postman" },
    ],
  },
];
